name: lexchoice
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.3.0
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.5
  smooth_page_indicator: ^1.2.0+3
  connectivity_plus: ^6.1.3
  lottie: ^3.3.1 
  flutter_launcher_icons: ^0.14.3

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.7.2
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2
  flutter_staggered_grid_view: ^0.7.0
  animated_background: ^2.0.0
  shared_preferences: ^2.5.2

  # Game video
  chewie: ^1.10.0
  cloudinary_public: ^0.23.1
  google_fonts: ^6.2.1
  audioplayers: ^6.4.0
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  animated_splash_screen: ^1.3.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/lexchoice_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/animations/
    - assets/images/thumbnails/
    - assets/images/splash/
    - assets/stories/lila/
    - assets/stories/ravi/
    - assets/stories/amy/
    - assets/stories/devin/
    - assets/stories/aarya/
    - assets/audio/
    - assets/avatars/
